//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generator.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public int Id { get; set; }
        public string Single { get; set; }
        public string Plural { get; set; }
        public string Meaning { get; set; }
    }
}
